#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: [classpath:/haha/]
  spring:
    redis:
      #超时时间
      timeout: 10000ms
      #服务器地址
      host: localhost
      #服务器端口
      port: 6379
      #数据库
      database: 0
      #密码 如redis设置有密码则取消注释并填写正确密码
#      password: 123456
      lettuce:
        pool:
          #最大连接数，默认8
          max-active: 1024
          #最大连接阻塞等待时间，默认-1
          max-wait: 10000ms
          #最大空闲连接
          max-idle: 200
          #最小空闲连接
          min-idle: 5

